### ISSUE TITLE
Add sound to the game

### ISSUE THREAD

**Issue by Raane** [ninjadev/globalgamejam2016#11]
The game has no sound :(

**Comment by iver56** [comment]
- [x] Architecture
- [x] Upgrade soundjs
- [ ] Personalized sounds. For example with stereo panning and loud sounds nearby.

## Sounds:
- [ ] Player hit
- [x] Shield hit
- [x] Dark bullet fired
- [x] Light bullet fired
- [ ] Bullet hit wall
- [x] Capture point taken by light team
- [x] Capture point taken by dark team
- [ ] Dark capture point lost (it is now somewhere between light and dark)
- [ ] Light capture point lost (it is now somewhere between light and dark)
- [ ] A sound for the process of taking over a capture point
- [x] Lost game
- [x] Won game
- [x] Trying to shoot while weapon is overheated
