### ISSUE TITLE
click.mp3 doesn't work in FireFox

### ISSUE THREAD

**Issue by iver56** [ninjadev/globalgamejam2016#183]

**Comment by sigvef** [comment]
But the other mp3s do?

**Comment by iver56** [comment]
Yep. The console in FF says that the file is corrupted, and the integrated player in FF won't play the sound when I try to open it directly in a separate tab.

Could it have anything to do with the short duration of the sound?

**Comment by iver56** [comment]
Fixed https://github.com/ninjadev/globalgamejam2016/commit/12eae2f5808b13c66e7e8b46e75d49215569e718
